### ISSUE TITLE
Análisis de esquema RUP - SNIES 

### ISSUE THREAD

**Issue by mariaalejandra9404** [udistrital/parametros_gobierno#1]
Dada la revisión realizada de las tablas en los diferentes esquemas Core existentes, se identificaron 6 tablas relacionadas con RUP (Registros Único de Proponentes) y 6 tablas relacionadas con SNIES (Sistema Nacional de Información de la Educación Superior), se requiere _evaluar su utilidad_, su _redundancia_, su _estructura_ y sus _datos actuales_ con el fin de **ajustarlas a los estándares de la OAS y reubicarlas en un nuevo esquema** (de ser necesario) que pertenecerá a la base de datos Core 

Criterios de aprobación

- [x] Script de SQL de esquema final
- [ ] Documentación generada por Schemaspy publicada en url determinada
- [x] Aprobación de equipo de Arquitectura y DBAs

**Comment by corio27** [comment]
Se válida porceso

**Comment by nodier25** [comment]
Buenos días

se evalúan los modelos de los esquemas que se van a ir al core y se hace las correcciones de agregar los campos de fecha_creacion, fecha_modificacion y colocar actualizado el modelo de bases de datos

Muchas gracias
