### ISSUE TITLE
Añadir tablas punto_salarial y salario_minimo a API parametros_gobierno

### ISSUE THREAD

**Issue by mariaalejandra9404** [udistrital/parametros_gobierno#21]
Dado el análisis realizado sobre las tablas que se consideraban parte de un posible esquema "variables globales", se decidó que la tabla punto_salarial y salario_minimo deberían ir en el API parametros_gobierno. De esta forma, se deben realizar las siguientes actividades

- [x] Crear archivos de beego migrate para crear tablas punto_salarial y salario_minimo
- [x] Revisión por parte de DBA de los scripts de las tablas propuestas
- [x] Jobs para migrar la información de las tablas 
- [x] Crear controlador y modelo de tablas aprobadas en API
- [x] Desplegar cambios en el 254

**Comment by nodier25** [comment]
Buen día se validan los cambio de los tres campos 

muchas gracias

**Comment by mariaalejandra9404** [comment]
Se corren cambios en Jenkins y API queda disponible en http://10.20.0.254:8205/v1/salario_minimo
