### ISSUE TITLE
Añadir tablas iva a API parametros_gobierno

### ISSUE THREAD

**Issue by AlaskaRising** [udistrital/parametros_gobierno#27]
Dado el análisis realizado por el equipo de trabajo: udistrital/necesidades-cliente/issues/23 , se decidió que la tabla _iva_ debería ir en el API parametros_gobierno. De esta forma, se deben realizar las siguientes actividades

- [x] Crear archivos de beego migrate para crear tabla iva
- [x] Revisión por parte de DBA de los scripts de la tabla propuesta
- [x] Crear controlador y modelo de tabla aprobado en API
- [x] Desplegar cambios en el 254

**Comment by AlaskaRising** [comment]
Se evalúa modelo de la tabla IVA con DBA's y se llega a la conclusión de que se requieren tablas mas generales para manejo de Impuestos, por lo que se va a plantear un nuevo modelo, para su evaluación y posterior implementación.

**Comment by macaguegi** [comment]
Se notifica a líder técnico @Soulfilip-UD dado que esta tarea se postergará hasta la otra semana mientras se define el nuevo modelo . :smile:

**Comment by mariaalejandra9404** [comment]
Se cierra Issue debido a lo hablado en la reunión y se procede a crear issues para nuevas tablas.
