### ISSUE TITLE
Añadir tablas relacionadas a IMPUESTOS a API parametros_gobierno 

### ISSUE THREAD

**Issue by mariaalejandra9404** [udistrital/parametros_gobierno#35]
Dada la reunión realizada con Arquitectura y Bases de Datos, se decidió prescindir de la tabla IVA y adoptar un modelo más general para el manejo de cualquier tipo de impuestos. Por esto, se proponen tres tablas:

1. **Tipo Impuesto**: Será una tabla paramétrica, según el lineamiento de bases de datos, que que tendrán los tipos de impuestos dispuestos por las normal nacionales.
2. **Impuesto**: Será una tabla paramétrica que alojará todos la información general de los subtitpos de impuestos existentes. Estos impuestos contarán con un tipo, asociado a la tabla del punto 1.
3. **Vigencia Impuestos**: Permitirá manejar el histórico de los valores de los impuestos, su fecha de entrada y salida de vigencia y su porcentaje de aplicación.

Para esto, se definen las siguientes tareas:

- [x]  Crear archivos de beego migrate para crear tabla iva
- [x]  Revisión por parte de DBA de los scripts de la tabla propuesta
- [x]  Crear controlador y modelo de tabla aprobado en API
- [x]  Desplegar cambios en el 254
- [x]  Desplegar cambios en test

**Comment by mariaalejandra9404** [comment]
Se organiza reunión con DBA y arquitectura para el día 22 de agosto a las 2pm con el fin de realizar revisión de los cambios realizados en el [commit](https://github.com/udistrital/parametros_gobierno/commit/90b95c96d625791aacf7aade758c16d292bc2b58)

**Comment by nodier25** [comment]
Buen día
 
Se revisan el modelo para el core de las tablas test y se ajustan a la normativa y son aprobados

Muchas gracias

**Comment by mariaalejandra9404** [comment]
Se realiza despliegue tanto en entorno dev:
como en entorno test: https://ci.portaloas.udistrital.edu.co/udistrital/parametros_gobierno/68
