### ISSUE TITLE
Añadir tablas relacionadas con CIIU

### ISSUE THREAD

**Issue by mariaalejandra9404** [udistrital/parametros_gobierno#36]
En la última reunión realizada con equipo de Arquitectura y Base de Datos, se acordó manejar las 4 tablas relacionadas con _CLASIFICACIÓN INDUSTRIAL INTERNACIONAL UNIFORME DE TODAS LAS ACTIVIDADES ECONÓMICAS_ (CIIU) por medio de solamente dos, las cuales se encuentran en el esquema **core** de la base de datos **udistrital_core_db**. Por esto, se realizarán las siguientes tareas para incluir estas dos tablas en el API: 

- [x]  Crear archivos de beego migrate para crear tablas
- [x]  Revisión por parte de DBA de los scripts de las tablas propuesta
- [x]  Crear controlador y modelo de tablas aprobado en API
- [x]  Desplegar cambios en el 254
- [x]  Desplegar cambios en test

**Comment by mariaalejandra9404** [comment]
Se realiza despliegue de migración de tablas de CIIU en 254: https://intelligentia.udistrital.edu.co:8443/jenkins/job/golang_api/935/console

**Comment by nodier25** [comment]
Buen día

Se aprueba el modelo después de la revisión

muchas gracias

**Comment by AlaskaRising** [comment]
Las tablas y la data correspondiente queda desplegada en pruebas
https://intelligentia.udistrital.edu.co:8443/jenkins/job/golang_api/936/console
y en test:https://ci.portaloas.udistrital.edu.co/udistrital/parametros_gobierno/68
