### ISSUE TITLE
Agregar Comentarios en todas las tablas y sus respectivos campos a nivel de BD

### ISSUE THREAD

**Issue by AlaskaRising** [udistrital/parametros_gobierno#38]
Con el fin de llevar buenas prácticas en la unificación y trabajo de base de datos, y para no acumular para el final, se decide agregar comentarios a todas las tablas creadas y a las columnas de cada una de ellas para que quienes las consulten tengan claridad de qué funciones cumplen ellas y cada uno de sus atributos. 

- [x] Migraciones que incluyen comentarios sobre tablas
- [x] Despliegue de cambios por medio de migrate en ambiente local (254-159)
- [x] Despliegue de cambios en TEST

**Comment by mariaalejandra9404** [comment]
Se realizó despliegue en 254 para aplicar cambios de comentarios en tablas
https://intelligentia.udistrital.edu.co:8443/jenkins/job/golang_api/935/console

**Comment by mariaalejandra9404** [comment]
Se realiza despliegue de este cambio en TEST:
https://ci.portaloas.udistrital.edu.co/udistrital/parametros_gobierno/68/4
