### ISSUE TITLE
Definición y creación de plan de transición a nuevo esquema parametros_gobierno

### ISSUE THREAD

**Issue by mariaalejandra9404** [udistrital/parametros_gobierno#7]
Dado que ya se encuentra creado el API y la base de datos que albergará las tablas relacionadas con RUP y SNIES, se debe definir cómo los diversos sistemas que usan estas tablas en los diferentes Core existentes pasarán a consultar las nuevas tablas y a usar el API creado. De esta manera, se definen las siguientes tareas

- [x] Para sistemas Sara, evaluar impacto dado el número de queries realizados a las tablas aquí mencionadas y proponer cómo se va a realizar el cambio de estas consultas para que apunten a base de datos y esquema nuevo

- [x] Para sistemas con nuevas tecnologías, evaluar impacto de consumo de tablas de por medio de APIs ya propuestos y proponer transición a nuevo API parámetros_gobierno

- [ ] Consignar plan de transición en documento

**Comment by mariaalejandra9404** [comment]
Se preguntó a encargados de sistemas SARA sobre el uso de tablas SNIES y RUP  y se reportó que se hace consulta de tablas snies_area y snies_nucleo_basico en: 

* agora/blocks/gestionCotizaciones/relacionarCotizacion/Sql.class.php 
* agora/blocks/gestionCotizaciones/gestionarValidaciones/Sql.class.php
* agora/blocks/gestionCotizaciones/gestionarValidacionModificar/Sql.class.php
* agora/blocks/gestionCotizaciones/gestionarCotizacion/Sql.class.php

No se reporta consulta de tablas RUP

**Comment by mariaalejandra9404** [comment]
Se realizó job en Talend para volcar datos a base de datos de pruebas. Esto con el fin de construir los queries que necesitan los sistemas de Sara para consultar las tablas SNIES_area y SNIES_nucleo basico. La idea es que nosotros les pasemos estas consultas, asegurándonos que arrojen los mismos resultados que ellos tienen y dejarlas consignadas en un documento para que, cuando exista base de datos de producción, ellos implementen estos cambios.

**Comment by AlaskaRising** [comment]
Se realizo documento en [Drive](https://drive.google.com/drive/folders/1E5zX-iDXT7YntyCiljlQkyg3fEXbYDCm) en el que se trabajan las consultas SQL manejadas en SARA en lenguaje PHP y SQL en sus dos verciones OLD y NEW correspondientes a la busqueda en la base de datos antigua y a la busqueda en la base de datos nueva de forma que arroje el mismo resultado esto para asegurar un correcto proceso de tansicion, se evaluo el uso de estas tablas en diversos aplicativos de la organizacion y queda pendiente hablar con Andrey para el proceso de transicion.

**Comment by mariaalejandra9404** [comment]
Junto con @AlaskaRising se realizó búsqueda en repos de organización UDISTRITAL para identificar cuáles consumian las tablas que fueron reemplazadas por este API. El resultado se consolidó en este documento [este documento](https://docs.google.com/spreadsheets/d/1O8YxU-5igN4IqnXAVaB-g8GzgbbujKyLijzWRRXbRGs/edit#gid=1305395270)

Así, basados en este documento, se crearon carpetas por repositorio incluyendo en ellas los archivos que deben ser reemplazados por cada equipo de trabajo para ahora consultar este API y las tablas nuevas propuestas. Las carpetas se encuentran [aquí](https://drive.google.com/drive/u/2/folders/1E5zX-iDXT7YntyCiljlQkyg3fEXbYDCm)

Se continuará luego con los clientes en Angular 7

**Comment by mariaalejandra9404** [comment]
Se completan las carpetas por cliente para cada una de las transiciones que se deben realizar para consumir el API parametros_gobierno:

0. Plan de transición para Agora [aquí](https://drive.google.com/drive/u/0/folders/1HftOq7fNlX1zAL2iG_oHtXeTBEUEN0xk)

1. Plan de transición para administrativa_cliente [aquí](https://drive.google.com/drive/u/0/folders/1eN9L6yxhuJ5xQ2YzYAI87v7lqepbM1pA)

2. Plan de transición para novedades_cliente [aquí](https://drive.google.com/drive/u/0/folders/1WwpGx2is70FjKzv6BTuHHu3B-Zs22nWW)

3. Plan de transición para resoluciones_cliente [aquí](https://drive.google.com/drive/u/0/folders/1HftOq7fNlX1zAL2iG_oHtXeTBEUEN0xk)

4. Plan de transición para polux_cliente [aquí](https://drive.google.com/drive/u/0/folders/14BfWdWZ8lJ0C5vcgZXmW--Sj-2dYie73)

5. Plan de transición para necesidades_cliente [aquí](https://drive.google.com/drive/u/0/folders/1R-lMEA8bDJwt1uUBED2SwS8s7fZd-g5v)

Para este caso, no se tienen que modificar clientes en Angular 7.

**Comment by mariaalejandra9404** [comment]
1. Se actualiza documento de plan de transición, ya que se incluyen tablas de **salario_minimo** y **punto_salarial**. Esto implicó modificar las carpetas ya definidas para: novedades_cliente,  
necesidades-cliente, administrativa_cliente y resoluciones_cliente, agregando dos archivos (contrato_registro y contrato_registro_horas). 

2. Además, se crearon dos nuevas carpetas, una para el cliente _cumplidos_cliente_ y otra para el API MID _administrativa_mid_api_. Para el mid api, se agregan nuevas variables de entorno (archivo app.conf) y se modifican consumos de servicios de core a servicios parametros_gobierno; se agrega en el archivo los valores que dichas variables de entorno deben tener en **dev** y **test**

3. Se consigna lo anterior en la hoja "Parametros_gobierno" del [documento en drive](https://docs.google.com/spreadsheets/d/1O8YxU-5igN4IqnXAVaB-g8GzgbbujKyLijzWRRXbRGs/edit#gid=1305395270)

**Comment by mariaalejandra9404** [comment]
Se consulta con Andrey para incluir en transición las consultas que los sistemas en SARA realizan a las tablas de salario mínimo y punto salarial. Andrey nos indicó que punto_salarial no se usa en estos sistemas y nos envió los archivos php que consultan el salario minimo:

agora/blocks/gestionCotizaciones/gestionarCotizacion/Sql.class.php    ---467
agora/blocks/gestionCotizaciones/gestionarValidaciones/Sql.class.php   ---341
agora/blocks/gestionCotizaciones/gestionarValidacionModificar/Sql.class.php  ---285
agora/blocks/gestionCotizaciones/relacionarCotizacion/Sql.class.php ---131
argo/blocks/gestionActas/gestionActasInicio/Sql.class.php ---1311
argo/blocks/gestionPolizas/gestionPolizas/Sql.class.php  --833

Así, se incluyen los procesos de transición en la carpeta:

1. Para sistema [Argo](https://drive.google.com/drive/u/0/folders/1cfLDrxWfg9dVrhpIq95p7dhZPA0kUFwv)
2. Para sistema [Agora](https://drive.google.com/drive/u/0/folders/1HftOq7fNlX1zAL2iG_oHtXeTBEUEN0xk)

En ambos casos, se incluyen archivos que cambian las consultas para consumir el nuevo esquema parametros_gobierno. Todo queda consignado en: https://docs.google.com/spreadsheets/d/1O8YxU-5igN4IqnXAVaB-g8GzgbbujKyLijzWRRXbRGs/edit#gid=1305395270

**Comment by mariaalejandra9404** [comment]
Se agrega a [archivo en carpeta](https://drive.google.com/drive/u/0/folders/1HftOq7fNlX1zAL2iG_oHtXeTBEUEN0xk) los queries para transición en Agora en dirección https://gogs.udistritaloas.edu.co/academica/funcionarios/src/master/agora/blocks/administracion/consultaGeneralProveedor/Sql.class.php

**Comment by mariaalejandra9404** [comment]
Las clases en PHP que se deben configurar por cada tabla de CIIU son:

--ciiu_clase

agora/blocks/administracion/consultaGeneralProveedor/Sql.class.php   ---1226
agora/blocks/gestionCotizaciones/gestionarCotizacion/Sql.class.php   ---1411 y 1774
agora/blocks/gestionCotizaciones/gestionarValidaciones/Sql.class.php   ---1288 y 1618
agora/blocks/gestionCotizaciones/gestionarValidacionModificar/Sql.class.php   --- 1232 y 1562
agora/blocks/gestionCotizaciones/relacionarCotizacion/Sql.class.php   ---  580 y 948
agora/blocks/proveedor/registroExtranjero/Sql.class.php  --1387
agora/blocks/proveedor/registroNotificaciones/Sql.class.php   --- 2068
agora/blocks/proveedor/registroProveedor/Sql.class.php  ---1509
argo/blocks/gestionCompras/consultaOrden/Sql.class.php  --- 2154
argo/blocks/gestionCompras/registrarServicioOrden/Sql.class.php --- 308
argo/blocks/gestionContractual/contratos/modificarContrato/Sql.class.php ---2057
argo/blocks/gestionContractual/registrarServicioContrato/Sql.class.php --229
argo/blocks/gestionNecesidades/gestionarNecesidadConTercero/Sql.class.php  ---293 y 609
argo/blocks/gestionNecesidades/gestionarNecesidadSinTercero/Sql.class.php  ---293 y 609
argo/blocks/gestionNecesidades/relacionarNecesidad/Sql.class.php ---293 y 609

---ciiu_division

agora/blocks/administracion/consultaGeneralProveedor/Sql.class.php ---1217
agora/blocks/gestionCotizaciones/gestionarCotizacion/Sql.class.php  ---1412 y 1765
agora/blocks/gestionCotizaciones/gestionarCotizacion/Sql.class.php --1289 y 1609
agora/blocks/gestionCotizaciones/gestionarValidacionModificar/Sql.class.php --1233 y 1553
agora/blocks/gestionCotizaciones/relacionarCotizacion/Sql.class.php  --- 581 y 939
agora/blocks/proveedor/registroExtranjero/Sql.class.php  ---1378
agora/blocks/proveedor/registroNotificaciones/Sql.class.php  ---2059
agora/blocks/proveedor/registroProveedor/Sql.class.php --1500
argo/blocks/gestionNecesidades/gestionarNecesidadConTercero/Sql.class.php  --294 y 600
argo/blocks/gestionNecesidades/gestionarNecesidadSinTercero/Sql.class.php  ---294 y 600
argo/blocks/gestionNecesidades/relacionarNecesidad/Sql.class.php  --294 y 600

---ciiu_subclase

agora/blocks/administracion/consultaGeneralProveedor/Sql.class.php  ---217, 426, 1236, 1247
agora/blocks/gestionCotizaciones/gestionarCotizacion/Sql.class.php  ---970,1410,1440,1450,1784,1833,1842
agora/blocks/gestionCotizaciones/gestionarValidaciones/Sql.class.php  ---877,1287,1317,1327,1628,1677,1686
agora/blocks/gestionCotizaciones/gestionarValidacionModificar/Sql.class.php --821,1231,1261,1271,1572,1621,1630
agora/blocks/gestionCotizaciones/relacionarCotizacion/Sql.class.php ---579,606,616,958,1006,1015,1027
agora/blocks/proveedor/registroExtranjero/Sql.class.php  ---405,1397,1408
agora/blocks/proveedor/registroNotificaciones/Sql.class.php  ---1009,2078,2088
agora/blocks/proveedor/registroProveedor/Sql.class.php ---125,142,435,1519,1530
argo/blocks/gestionCompras/consultaOrden/Sql.class.php ---2158,2162
argo/blocks/gestionCompras/registrarServicioOrden/Sql.class.php  ---312
argo/blocks/gestionContractual/contratos/modificarContrato/Sql.class.php ---2061,2065
argo/blocks/gestionContractual/registrarServicioContrato/Sql.class.php ---233
argo/blocks/gestionNecesidades/gestionarNecesidadConTercero/Sql.class.php ---292,319,329,619
argo/blocks/gestionNecesidades/gestionarNecesidadSinTercero/Sql.class.php --292,,319,329,619
argo/blocks/gestionNecesidades/relacionarNecesidad/Sql.class.php  --292,,319,329,619

**Comment by mariaalejandra9404** [comment]
Se intenta acceder a las direcciones señaladas en el comentario anterior pero no cuento con permisos para hacerlo. Parece que se borraron. Se le comenta a Fernando para darle solución a esto.
![image](https://user-images.githubusercontent.com/8922367/63970088-d2ab7a00-ca92-11e9-8122-4cdfb6354093.png)

**Comment by AlaskaRising** [comment]
Junto con @mariaalejandra9404 se inicio el plan de transición para las consultas de ciiu_subclase, el estado de cambio de consultas actual corresponde al siguiente:

- [3/4] agora/blocks/administracion/consultaGeneralProveedor/Sql.class.php ---217, 426, 1236, 1247
- [4/7] agora/blocks/gestionCotizaciones/gestionarCotizacion/Sql.class.php ---970,1410,1440,1450,1784,1833,1842
- [4/7] agora/blocks/gestionCotizaciones/gestionarValidaciones/Sql.class.php ---877,1287,1317,1327,1628,1677,1686
- [4/7] agora/blocks/gestionCotizaciones/gestionarValidacionModificar/Sql.class.php --821,1231,1261,1271,1572,1621,1630
- [4/7] agora/blocks/gestionCotizaciones/relacionarCotizacion/Sql.class.php ---579,606,616,958,1006,1015,1027
- [2/3] agora/blocks/proveedor/registroExtranjero/Sql.class.php ---405,1397,1408
- [2/3] agora/blocks/proveedor/registroNotificaciones/Sql.class.php ---1009,2078,2088
- [4/5] agora/blocks/proveedor/registroProveedor/Sql.class.php ---125,142,435,1519,1530
- [2/2] argo/blocks/gestionCompras/consultaOrden/Sql.class.php ---2158,2162
- [1/1] argo/blocks/gestionCompras/registrarServicioOrden/Sql.class.php ---312
- [2/2] argo/blocks/gestionContractual/contratos/modificarContrato/Sql.class.php ---2061,2065
- [1/1] argo/blocks/gestionContractual/registrarServicioContrato/Sql.class.php ---233
- [1/4] argo/blocks/gestionNecesidades/gestionarNecesidadConTercero/Sql.class.php ---292,319,329,619
- [1/4] argo/blocks/gestionNecesidades/gestionarNecesidadSinTercero/Sql.class.php --292,319,329,619
- [1/4] argo/blocks/gestionNecesidades/relacionarNecesidad/Sql.class.php --292,,319,329,619

Se sube archivo al Drive - Bases de datos - Parámetros gobierno - Transición Agora

**Comment by AlaskaRising** [comment]
Junto a @mariaalejandra9404  se sigue trabajando en las consultas restantes de ciiu_subclase, y se adelantan consultas correspondientes a ciiu_division de la siguiente forma:

[1/1] agora/blocks/administracion/consultaGeneralProveedor/Sql.class.php ---1217
[1/2] agora/blocks/gestionCotizaciones/gestionarCotizacion/Sql.class.php ---1412 y 1765
[1/2] agora/blocks/gestionCotizaciones/gestionarCotizacion/Sql.class.php --1289 y 1609
[1/2] agora/blocks/gestionCotizaciones/gestionarValidacionModificar/Sql.class.php --1233 y 1553
[1/2] agora/blocks/gestionCotizaciones/relacionarCotizacion/Sql.class.php --- 581 y 939
[1/1] agora/blocks/proveedor/registroExtranjero/Sql.class.php ---1378
[1/1] agora/blocks/proveedor/registroNotificaciones/Sql.class.php ---2059
[1/1] agora/blocks/proveedor/registroProveedor/Sql.class.php --1500
[1/2] argo/blocks/gestionNecesidades/gestionarNecesidadConTercero/Sql.class.php --294 y 600
[1/2] argo/blocks/gestionNecesidades/gestionarNecesidadSinTercero/Sql.class.php ---294 y 600
[1/2] argo/blocks/gestionNecesidades/relacionarNecesidad/Sql.class.php --294 y 600

Se sube archivo al Drive - Bases de datos - Parámetros gobierno - Transición Agora

**Comment by mariaalejandra9404** [comment]
Con @AlaskaRising, se actualiza el archivo de Proceso-transición-Ágora por el nombre de "Snies-salari mínimo", haciendo alusión a las tablas que se están modificando. 

También, se agrega archivo para la tabla **ciiu_clase** y un archivo llamado **ágora-todo**, donde hay algunas consultas de más que pueden ser utiles para las que aún faltan

[1/1] agora/blocks/administracion/consultaGeneralProveedor/Sql.class.php ---1226
[1/2] agora/blocks/gestionCotizaciones/gestionarCotizacion/Sql.class.php ---1411 y 1774
[1/2] agora/blocks/gestionCotizaciones/gestionarValidaciones/Sql.class.php ---1288 y 1618
[1/2] agora/blocks/gestionCotizaciones/gestionarValidacionModificar/Sql.class.php --- 1232 y 1562
[1/2] agora/blocks/gestionCotizaciones/relacionarCotizacion/Sql.class.php --- 580 y 948
[1/1] agora/blocks/proveedor/registroExtranjero/Sql.class.php --1387
[1/1] agora/blocks/proveedor/registroNotificaciones/Sql.class.php --- 2068
[1/1] agora/blocks/proveedor/registroProveedor/Sql.class.php ---1509
[1/1] argo/blocks/gestionCompras/consultaOrden/Sql.class.php --- 2154
[1/1] argo/blocks/gestionCompras/registrarServicioOrden/Sql.class.php --- 308
[1/1]  argo/blocks/gestionContractual/contratos/modificarContrato/Sql.class.php ---2057
[1/1] argo/blocks/gestionContractual/registrarServicioContrato/Sql.class.php --229
[1/2] argo/blocks/gestionNecesidades/gestionarNecesidadConTercero/Sql.class.php ---293 y 609
[1/2] argo/blocks/gestionNecesidades/gestionarNecesidadSinTercero/Sql.class.php ---293 y 609
[1/2] argo/blocks/gestionNecesidades/relacionarNecesidad/Sql.class.php ---293 y 609

Puede consultarse los archivos descritos [aquí](https://drive.google.com/drive/u/2/folders/1HftOq7fNlX1zAL2iG_oHtXeTBEUEN0xk)

**Comment by AlaskaRising** [comment]
El día de hoy hablando con @blacburn , se evidencio que algunas de las consultas de Agora usan campos que no existen por lo que queda pendiente para revisión.

**Comment by mariaalejandra9404** [comment]
Se realiza transición con respecto a la tabla actividad_economica, en los siguientes clientes:

1. cumplidos_cliente
2. necesidades_cliente
3. resoluciones_cliente
4. novedades_cliente
5. administrativa_cliente

Se suben archivos a [carpeta](https://drive.google.com/drive/u/0/folders/1E5zX-iDXT7YntyCiljlQkyg3fEXbYDCm)

**Comment by mariaalejandra9404** [comment]
Este plan de transición se culminó y en este momento se está a la espera de que los equipos encargados de ejecutarlo estén disponibles para hacerlo. Por esto, se envía a Sprint y la ejecución del plan se realizará en otro issue.
